name: Release to GitHub Pages
run-name: Release to GitHub Pages
on: [push]
jobs:
  Use-Container:
    runs-on: ubuntu-latest
    container: python:3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python main.py
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html